/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AboutRouteImport } from './routes/about'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as CouplesRouteImport } from './routes/couples'
import { Route as FilmsRouteImport } from './routes/films'
import { Route as PackagesRouteImport } from './routes/packages'
import { Route as PortfolioRouteImport } from './routes/portfolio'
import { Route as PrivacyPolicyRouteImport } from './routes/privacy-policy'
import { Route as TermsOfServiceRouteImport } from './routes/terms-of-service'
import { Route as TestimonialsRouteImport } from './routes/testimonials'
import { Route as WeddingStoriesRouteImport } from './routes/wedding-stories'
import { Route as CouplesSlugRouteImport } from './routes/couples/$slug'
import { Route as WeddingStoriesIndexRouteImport } from './routes/wedding-stories/index'
import { Route as WeddingStoriesSlugRouteImport } from './routes/wedding-stories/$slug'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const CouplesRoute = CouplesRouteImport.update({
  id: '/couples',
  path: '/couples',
  getParentRoute: () => rootRouteImport,
} as any)
const FilmsRoute = FilmsRouteImport.update({
  id: '/films',
  path: '/films',
  getParentRoute: () => rootRouteImport,
} as any)
const PackagesRoute = PackagesRouteImport.update({
  id: '/packages',
  path: '/packages',
  getParentRoute: () => rootRouteImport,
} as any)
const PortfolioRoute = PortfolioRouteImport.update({
  id: '/portfolio',
  path: '/portfolio',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyPolicyRoute = PrivacyPolicyRouteImport.update({
  id: '/privacy-policy',
  path: '/privacy-policy',
  getParentRoute: () => rootRouteImport,
} as any)
const TermsOfServiceRoute = TermsOfServiceRouteImport.update({
  id: '/terms-of-service',
  path: '/terms-of-service',
  getParentRoute: () => rootRouteImport,
} as any)
const TestimonialsRoute = TestimonialsRouteImport.update({
  id: '/testimonials',
  path: '/testimonials',
  getParentRoute: () => rootRouteImport,
} as any)
const WeddingStoriesRoute = WeddingStoriesRouteImport.update({
  id: '/wedding-stories',
  path: '/wedding-stories',
  getParentRoute: () => rootRouteImport,
} as any)
const CouplesSlugRoute = CouplesSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => CouplesRoute,
} as any)
const WeddingStoriesIndexRoute = WeddingStoriesIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => WeddingStoriesRoute,
} as any)
const WeddingStoriesSlugRoute = WeddingStoriesSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => WeddingStoriesRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/contact': typeof ContactRoute
  '/couples': typeof CouplesRouteWithChildren
  '/films': typeof FilmsRoute
  '/packages': typeof PackagesRoute
  '/portfolio': typeof PortfolioRoute
  '/privacy-policy': typeof PrivacyPolicyRoute
  '/terms-of-service': typeof TermsOfServiceRoute
  '/testimonials': typeof TestimonialsRoute
  '/wedding-stories': typeof WeddingStoriesRouteWithChildren
  '/couples/$slug': typeof CouplesSlugRoute
  '/wedding-stories/$slug': typeof WeddingStoriesSlugRoute
  '/wedding-stories/': typeof WeddingStoriesIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/contact': typeof ContactRoute
  '/couples': typeof CouplesRouteWithChildren
  '/films': typeof FilmsRoute
  '/packages': typeof PackagesRoute
  '/portfolio': typeof PortfolioRoute
  '/privacy-policy': typeof PrivacyPolicyRoute
  '/terms-of-service': typeof TermsOfServiceRoute
  '/testimonials': typeof TestimonialsRoute
  '/couples/$slug': typeof CouplesSlugRoute
  '/wedding-stories/$slug': typeof WeddingStoriesSlugRoute
  '/wedding-stories': typeof WeddingStoriesIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/contact': typeof ContactRoute
  '/couples': typeof CouplesRouteWithChildren
  '/films': typeof FilmsRoute
  '/packages': typeof PackagesRoute
  '/portfolio': typeof PortfolioRoute
  '/privacy-policy': typeof PrivacyPolicyRoute
  '/terms-of-service': typeof TermsOfServiceRoute
  '/testimonials': typeof TestimonialsRoute
  '/wedding-stories': typeof WeddingStoriesRouteWithChildren
  '/couples/$slug': typeof CouplesSlugRoute
  '/wedding-stories/$slug': typeof WeddingStoriesSlugRoute
  '/wedding-stories/': typeof WeddingStoriesIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/contact'
    | '/couples'
    | '/films'
    | '/packages'
    | '/portfolio'
    | '/privacy-policy'
    | '/terms-of-service'
    | '/testimonials'
    | '/wedding-stories'
    | '/couples/$slug'
    | '/wedding-stories/$slug'
    | '/wedding-stories/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/contact'
    | '/couples'
    | '/films'
    | '/packages'
    | '/portfolio'
    | '/privacy-policy'
    | '/terms-of-service'
    | '/testimonials'
    | '/couples/$slug'
    | '/wedding-stories/$slug'
    | '/wedding-stories'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/contact'
    | '/couples'
    | '/films'
    | '/packages'
    | '/portfolio'
    | '/privacy-policy'
    | '/terms-of-service'
    | '/testimonials'
    | '/wedding-stories'
    | '/couples/$slug'
    | '/wedding-stories/$slug'
    | '/wedding-stories/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  ContactRoute: typeof ContactRoute
  CouplesRoute: typeof CouplesRouteWithChildren
  FilmsRoute: typeof FilmsRoute
  PackagesRoute: typeof PackagesRoute
  PortfolioRoute: typeof PortfolioRoute
  PrivacyPolicyRoute: typeof PrivacyPolicyRoute
  TermsOfServiceRoute: typeof TermsOfServiceRoute
  TestimonialsRoute: typeof TestimonialsRoute
  WeddingStoriesRoute: typeof WeddingStoriesRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/couples': {
      id: '/couples'
      path: '/couples'
      fullPath: '/couples'
      preLoaderRoute: typeof CouplesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/films': {
      id: '/films'
      path: '/films'
      fullPath: '/films'
      preLoaderRoute: typeof FilmsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/packages': {
      id: '/packages'
      path: '/packages'
      fullPath: '/packages'
      preLoaderRoute: typeof PackagesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/portfolio': {
      id: '/portfolio'
      path: '/portfolio'
      fullPath: '/portfolio'
      preLoaderRoute: typeof PortfolioRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy-policy': {
      id: '/privacy-policy'
      path: '/privacy-policy'
      fullPath: '/privacy-policy'
      preLoaderRoute: typeof PrivacyPolicyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/terms-of-service': {
      id: '/terms-of-service'
      path: '/terms-of-service'
      fullPath: '/terms-of-service'
      preLoaderRoute: typeof TermsOfServiceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/testimonials': {
      id: '/testimonials'
      path: '/testimonials'
      fullPath: '/testimonials'
      preLoaderRoute: typeof TestimonialsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/wedding-stories': {
      id: '/wedding-stories'
      path: '/wedding-stories'
      fullPath: '/wedding-stories'
      preLoaderRoute: typeof WeddingStoriesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/couples/$slug': {
      id: '/couples/$slug'
      path: '/$slug'
      fullPath: '/couples/$slug'
      preLoaderRoute: typeof CouplesSlugRouteImport
      parentRoute: typeof CouplesRoute
    }
    '/wedding-stories/': {
      id: '/wedding-stories/'
      path: '/'
      fullPath: '/wedding-stories/'
      preLoaderRoute: typeof WeddingStoriesIndexRouteImport
      parentRoute: typeof WeddingStoriesRoute
    }
    '/wedding-stories/$slug': {
      id: '/wedding-stories/$slug'
      path: '/$slug'
      fullPath: '/wedding-stories/$slug'
      preLoaderRoute: typeof WeddingStoriesSlugRouteImport
      parentRoute: typeof WeddingStoriesRoute
    }
  }
}

interface CouplesRouteChildren {
  CouplesSlugRoute: typeof CouplesSlugRoute
}

const CouplesRouteChildren: CouplesRouteChildren = {
  CouplesSlugRoute: CouplesSlugRoute,
}

const CouplesRouteWithChildren =
  CouplesRoute._addFileChildren(CouplesRouteChildren)

interface WeddingStoriesRouteChildren {
  WeddingStoriesSlugRoute: typeof WeddingStoriesSlugRoute
  WeddingStoriesIndexRoute: typeof WeddingStoriesIndexRoute
}

const WeddingStoriesRouteChildren: WeddingStoriesRouteChildren = {
  WeddingStoriesSlugRoute: WeddingStoriesSlugRoute,
  WeddingStoriesIndexRoute: WeddingStoriesIndexRoute,
}

const WeddingStoriesRouteWithChildren = WeddingStoriesRoute._addFileChildren(
  WeddingStoriesRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  ContactRoute: ContactRoute,
  CouplesRoute: CouplesRouteWithChildren,
  FilmsRoute: FilmsRoute,
  PackagesRoute: PackagesRoute,
  PortfolioRoute: PortfolioRoute,
  PrivacyPolicyRoute: PrivacyPolicyRoute,
  TermsOfServiceRoute: TermsOfServiceRoute,
  TestimonialsRoute: TestimonialsRoute,
  WeddingStoriesRoute: WeddingStoriesRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
